# Generated by Django 5.1.2 on 2024-11-22 04:32

import django.db.models.deletion
import first_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_received_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_number', models.CharField(max_length=10, validators=[first_app.models.validate_indian_phone_number])),
                ('patient_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.doctor')),
            ],
        ),
    ]
