# Generated by Django 5.1.2 on 2024-11-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_bookk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookk',
            old_name='doc_name',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doc_name',
            new_name='doctor_name',
        ),
    ]
