# Generated by Django 5.1.2 on 2024-11-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_rename_doc_name_bookk_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_image',
            field=models.ImageField(default='default.jpg', upload_to='departments'),
        ),
    ]
